# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doi',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
