# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_confrence_organised',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_consultancy_projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_event_organized',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_expert_lectures',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_keynote_address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_patents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_research_projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_session_chair',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_techtransfer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emp_visits',
            name='user',
        ),
    ]
