# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0002_auto_20171007_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_projects',
            name='co_pi',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='financial_outlay',
            field=models.CharField(default=' ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='funding_agency',
            field=models.CharField(default=' ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='pi',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='ptype',
            field=models.CharField(default='Research', max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='status',
            field=models.CharField(choices=[('Awarded', 'Awarded'), ('Submitted', 'Submitted'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='title',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
