# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0003_auto_20171031_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='l_type',
            field=models.CharField(choices=[('Expert Lecture', 'Expert Lecture'), ('Invited Talk', 'Invited Talk')], default='Expert Lecture', max_length=14),
        ),
    ]
