# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0003_auto_20171007_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_projects',
            name='title',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
