# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0004_auto_20171007_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_research_papers',
            name='user',
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doc_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doc_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='is_sci',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='issn_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='page_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Accepted', 'Accepted'), ('Communicated', 'Communicated')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='venue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='volume_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='funding_agency',
            field=models.CharField(default=' ', max_length=250, null=True),
        ),
    ]
