# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0007_auto_20171007_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_published_books',
            name='user',
        ),
        migrations.AlterField(
            model_name='emp_published_books',
            name='p_type',
            field=models.CharField(choices=[('Book', 'Book'), ('Monograph', 'Monograph'), ('Book Chapter', 'Book Chapter'), ('Handbook', 'Handbook'), ('Technical Report', 'Technical Report')], max_length=15),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Accepted', 'Accepted'), ('Communicated', 'Communicated')], max_length=15, null=True),
        ),
    ]
