# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0008_auto_20171008_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_patents',
            old_name='pyear',
            new_name='p_year',
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='p_no',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='status',
            field=models.CharField(choices=[('Filed', 'Filed'), ('Granted', 'Granted'), ('Published', 'Published'), ('Owned', 'Owned')], max_length=15),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
