# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0010_auto_20171009_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_mtechphd_thesis',
            old_name='cosupervisors',
            new_name='co_supervisors',
        ),
    ]
