# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0011_auto_20171009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='isbn_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='page_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='type',
            field=models.CharField(choices=[('Keynote', 'Keynote'), ('Plenary Address', 'Plenary Address')], max_length=1),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
