# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0012_auto_20171009_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='l_type',
            field=models.CharField(choices=[('Expert Lecture', 'Expert Lecture'), ('Invited Talk', 'Invited Talk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='type',
            field=models.CharField(blank=True, choices=[('Keynote', 'Keynote'), ('Plenary Address', 'Plenary Address')], max_length=1, null=True),
        ),
    ]
