# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0014_auto_20171009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_event_organized',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='role',
            field=models.CharField(choices=[('Convener', 'Convener'), ('Coordinator', 'Coordinator'), ('Co-Convener', 'Co-Convener')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='sponsoring_agency',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='type',
            field=models.CharField(choices=[('Training Program', 'Training Program'), ('Seminar', 'Seminar'), ('Short Term Program', 'Short Term Program'), ('Workshop', 'Workshop'), ('Any Other', 'Any Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
