# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0015_auto_20171009_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='consultants',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
