# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0016_auto_20171009_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='pf_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='role2',
            field=models.CharField(blank=True, choices=[('Chairman/Chairperson', 'Chairman/Chairperson'), ('Convener', 'Convener'), ('Co-ordinator', 'Co-ordinator'), ('Secretary', 'Secretary'), ('Joint-Secretary', 'Joint-Secretary'), ('Joint-Secretary-Cum-Treasurer', 'Joint-Secretary-Cum-Treasurer'), ('Treasurer', 'Treasurer'), ('Any Other', 'Any Other')], max_length=20, null=True),
        ),
    ]
