# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0017_auto_20171009_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='role2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
