# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0018_auto_20171009_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='k_year',
            field=models.IntegerField(choices=[(1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], max_length=4, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='role1',
            field=models.CharField(blank=True, choices=[('Advisary Committee', 'Advisary Committee'), ('Program Committee', 'Program Committee'), ('Organised', 'Organised'), ('Conference Chair', 'Conference Chair'), ('Any Other', 'Any Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='venue',
            field=models.CharField(max_length=50),
        ),
    ]
