# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0019_auto_20171009_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
