# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0021_auto_20171009_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='rtype',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Confrence', 'Confrence')], max_length=50),
        ),
    ]
