# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0022_auto_20171010_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='rtype',
            field=models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference')], default='Conference', max_length=50),
        ),
    ]
