# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0025_auto_20171024_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_consultancy_projects',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_event_organized',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_expert_lectures',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_mtechphd_thesis',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_patents',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_published_books',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_papers',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_research_projects',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_session_chair',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_techtransfer',
            name='date_entry',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='emp_visits',
            name='entry_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
