# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0027_auto_20171024_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_keynote_address',
            name='type',
            field=models.CharField(blank=True, choices=[('Keynote', 'Keynote'), ('Plenary Address', 'Plenary Address')], max_length=14, null=True),
        ),
    ]
