# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0033_auto_20171025_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_research_papers',
            name='doi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
