# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0035_auto_20171025_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_confrence_organised',
            name='role1',
            field=models.CharField(blank=True, choices=[('Advisary Committee', 'Advisary Committee'), ('Program Committee', 'Program Committee'), ('Organised', 'Organised'), ('Conference Chair', 'Conference Chair'), ('Any Other', 'Any Other')], default='Any Other', max_length=20, null=True),
        ),
    ]
