# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eis', '0037_auto_20171028_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=1000)),
                ('doj', models.DateField(default=datetime.datetime.now)),
                ('education', models.TextField(max_length=500)),
                ('interest', models.TextField(max_length=500)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
