# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eis', '0038_faculty_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_about',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
